### PR TITLE
Update example JSON files as Ahoy DTU REST API has changed (Ahoy v0.5.93+)

### PR DESCRIPTION
**Pull request by GallusMax**
/live now contains descriptive data only
/record/live has the current values in changed format

PLUS: inverter/total is missing, leaving summing up the P_AC values of each connected inverter to the client.

### CODE REVIEW

**Comment by henne49** [comment]
@dsteinkopf does this change need a change in reading the values in our skript as well?

**Comment by GallusMax** [comment]
Add: the values from /api/live seem to have moved to /api/inverter/id/[0..9] (see https://github.com/lumapu/ahoy/issues/737) 
Still unclear: is there a sum of _all_ connected inverters?

**Comment by dsteinkopf** [comment]
> @dsteinkopf does this change need a change in reading the values in our skript as well?

Yes, according to the above link, that affects Ahoy version 0.93+ and we will need one call + one for every installed inverter 👎 

I'd propose to wait for this all to be clear and more stable.

**Comment by dsteinkopf** [comment]
@GallusMax was so kind to provide two sample JSON outputs from the new version. I assume:

- API call to `.../api/live' -> [ahoy_development_api-live.json](https://github.com/henne49/dbus-opendtu/pull/54/files#diff-4d0b2e14f7153203229ab786bf3c12d2318cba484b63672bbf254b4aa2ce8671)
- API call to `.../api/record/live` -> [ahoy_development_api-record-live.json](https://github.com/henne49/dbus-opendtu/pull/54/files#diff-668ce72acb8137073123d3c30e7ed0a502a045708352b37409ad8da106ee2a16)

Could someone also contribute the output of `.../api/inverter/id/0` here? I would like to get an overview of what need to be changed first, before I update my own Ahoy.

**Comment by GallusMax** [comment]
> @GallusMax was so kind to provide two sample JSON outputs from the new version. I assume:
> 
>     * API call to `.../api/live` -> [ahoy_development_api-live.json](https://github.com/henne49/dbus-opendtu/pull/54/files#diff-4d0b2e14f7153203229ab786bf3c12d2318cba484b63672bbf254b4aa2ce8671)
> 
>     * API call to `.../api/record/live` -> [ahoy_development_api-record-live.json](https://github.com/henne49/dbus-opendtu/pull/54/files#diff-668ce72acb8137073123d3c30e7ed0a502a045708352b37409ad8da106ee2a16)
> 
> 
> Could someone also contribute the output of `.../api/inverter/id/0` here? I would like to get an overview of what need to be changed first, before I update my own Ahoy.

Sure: I have added a file to the patch showing output by pre-release version 0.5.105. Thanks for your engagement!

**Comment by dsteinkopf** [comment]
Thank you, I'll have a look at it soon. If you have any additional information or insights that could help, just let us know

**Review by dsteinkopf — APPROVED** [review]

**Comment by dsteinkopf** [comment]
Merged this PR.
Code updates for the new API structure will follow in a separate PR.

**Comment by dsteinkopf** [comment]
@GallusMax I am currently trying the implementation. Could you please re-check the output of the record API call? The example file currently contains the values more than once per Inverter, and I don't know which one to take. E.g. YieldTotal for inverter 0: 96.27, 99.01, 98.77, 392.96
Is this an error in the Ahoy implementation or in the example file?

**Comment by dsteinkopf** [comment]
continue in #65

**Pull request merged**
