### PR TITLE
SetupHelper support

### PR DESCRIPTION
**Pull request by herrfrei**
I added and tested SetupHelper (https://github.com/kwindrem/SetupHelper) support for dbus-opendtu. Several files were added for that - some must be adjusted in the base repo:

- `gitHubInfo`: owner and release tag (now **herrfrei:latest**, should be modified to **henne49:latest** or any tag you prefer)
- `changes`: version number and short release description
- `version`: version number of current release
I'm not sure if the release must be numbered as vMAJOR.MINOR, but SetupHelper uses this scheme also. 

For some other files I added the executable flag to the git repo, the `services/run` file is replaced by a simpler file.

Most **important** change is the **renaming** of `config.ini` to `config.ini.sample` to not overwrite any existing customized file on package update. This is (shortly) described in the readme file.

### CODE REVIEW

**Comment by henne49** [comment]
Thank you very much for this pull request, I'm currently reviewing and trying to get it working for me, can you include a working example and changes as proposed from your side into, so we can test and merge?

gitHubInfo: owner and release tag (now herrfrei:latest, should be modified to henne49:latest or any tag you prefer)
changes: version number and short release description
version: version number of current release
I'm not sure if the release must be numbered as vMAJOR.MINOR, but SetupHelper uses this scheme also

**Comment by henne49** [comment]
and how do I install the dbus-opendtu, once I have installed setuphelper?

**Comment by herrfrei** [comment]
I tried to create a short installation tutorial. Since I have it already installed from my repo, the last steps are missing:

- Install SetupHelper according to https://github.com/kwindrem/SetupHelper
- Select 'Package manager' page 
setup-1
- Go to 'Inactive packages' 
setup-2
- Select 'new' 
setup-3
- Enter the repo details 
setup-4
- Press OK
- Go back to 'Active packages' 
setup-5
- Select 'dbus-opendtu' 
setup-6
- The following page will look different for you! Select 'Download' -> 'Proceed', after that 'Install' -> 'Proceed'. 
setup-7
- The package should be installed now. Since the configuration file is missing after installation (but not after later upgrade), do the following:
  - Copy `/data/dbus-opendtu/config.ini.sample` to `/data/dbus-opendtu/config.ini` and adapt it to your requirements.
  - Stop the dbus-opendtu service if it is running: `svc -d /service/dbus-opendtu`
  - Start it again: `svc -u /service/dbus-opendtu`

Hope this is complete and understandable.

**Comment by herrfrei** [comment]
Okay, I'll take a look at that. Since you are willing to rename the config.ini, the other problems seem to be solvable.  What do you think about semantic versioning? Is this also possible?

**Comment by henne49** [comment]
we went for Calendar Versioning, and it would be time for a new release soon. I do not understand the versioning in context to your PR, can you explain?

**Comment by herrfrei** [comment]
Yes, sure. Please take a look at the screenshot.

image

The version number is really long. May be we can ask to adjust SetupHelper. But this needs to increase all three version columns and reduces place for the package name.

**Comment by herrfrei** [comment]
Hi, this looks better. I tried with a long version (2023.12.29) and will ask the author of SetupHelper to increase the fields a little bit. 
Then I will adapt this PR as requested (unchanged run files etc.).

sh-version-number

**Comment by henne49** [comment]
https://github.com/henne49/dbus-opendtu/releases/tag/1.0.0 changed to semantic versioning

**Comment by dsteinkopf** [comment]
Will it be a problem that this version starts with a “1” while the previous versions start with “2” - which is larger?

**Comment by henne49** [comment]
I changed all older releases back and set the pre-release tag/flag

**Comment by henne49** [comment]
yes we changed to v1.0.0 ignore the old ones

grafik

**Comment by henne49** [comment]
I have now also deleted all old non compliant version numbering
grafik

**Comment by henne49** [comment]
@herrfrei did you submit all changes as requested? Not sure I'm up2date

**Comment by herrfrei** [comment]
@henne49 No, I think not. As discussed above, I shoud revert the run scripts and want to check every change again. Right now I have not enough time for that. So please be patient.

**Comment by henne49** [comment]
OK you are welcome, I just did not want to be the showstopper, take the time you need!

**Pull request closed without merging**
