### PR TITLE
Added Video Link

### PR DESCRIPTION
**Pull request by henne49**

### CODE REVIEW

**Comment by stxShadow** [comment]
Hi Henne49,
i've installed the new version on my testsystem. 

At first i had a problem with "cm?cmnd=status%208" in the config.ini -> changed it to cm?cmnd=status 8.
Seems to work now. As it is darf outside i get only values for voltage and total. Total is not acutally show in the 
VenusOS gui (shown on the screenshot).

Will report back tomorrow.

Debug Log output:

2023-01-02 22:17:01,656 urllib3.connectionpool DEBUG Starting new HTTP connection (1): 192.168.178.102:80
2023-01-02 22:17:01,780 urllib3.connectionpool DEBUG http://192.168.178.102:80 "GET /cm?cmnd=status%208 HTTP/1.1" 200 None
2023-01-02 22:17:01,801 root DEBUG OpenDTU Power (/Ac/Power): 0.0
2023-01-02 22:17:01,803 root DEBUG OpenDTU Energy (/Ac/Energy/Forward): 1618.264
2023-01-02 22:17:01,805 root DEBUG ---
2023-01-02 22:17:03,657 urllib3.connectionpool DEBUG Starting new HTTP connection (1): 192.168.178.102:80
2023-01-02 22:17:03,907 urllib3.connectionpool DEBUG http://192.168.178.102:80 "GET /cm?cmnd=status%208 HTTP/1.1" 200 None
2023-01-02 22:17:03,927 root DEBUG OpenDTU Power (/Ac/Power): 0.0
2023-01-02 22:17:03,928 root DEBUG OpenDTU Energy (/Ac/Energy/Forward): 1618.264
2023-01-02 22:17:03,929 root DEBUG ---
2023-01-02 22:17:04,331 root DEBUG _get_value_handler called for /
2023-01-02 22:17:04,333 root DEBUG {'Mgmt/ProcessName': dbus.String('/data/dbus-opendtu/dbus-opendtu.py', variant_level=1), 'Mgmt/ProcessVersion': dbus.String('Unkown version, and running on Python 3.8.13', variant_level=1), 'Mgmt/Connection': dbus.String('OpenDTU HTTP JSON service', variant_level=1), 'DeviceInstance': dbus.Int32(34, variant_level=1), 'ProductId': dbus.Int32(65535, variant_level=1), 'ProductName': dbus.String('OpenDTU', variant_level=1), 'CustomName': dbus.String('Tasmota-Growatt', variant_level=1), 'Connected': dbus.Int32(1, variant_level=1), 'Latency': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'FirmwareVersion': dbus.Double(0.1, variant_level=1), 'HardwareVersion': dbus.Int32(0, variant_level=1), 'Position': dbus.Int32(1, variant_level=1), 'Serial': dbus.String('12345678', variant_level=1), 'UpdateIndex': dbus.Int32(2, variant_level=1), 'StatusCode': dbus.Int32(0, variant_level=1), 'Ac/Energy/Forward': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/Power': dbus.Int32(0, variant_level=1), 'Ac/L1/Voltage': dbus.Double(235.0, variant_level=1), 'Ac/L2/Voltage': dbus.Int32(0, variant_level=1), 'Ac/L3/Voltage': dbus.Int32(0, variant_level=1), 'Ac/L1/Current': dbus.Int32(0, variant_level=1), 'Ac/L2/Current': dbus.Int32(0, variant_level=1), 'Ac/L3/Current': dbus.Int32(0, variant_level=1), 'Ac/L1/Power': dbus.Int32(0, variant_level=1), 'Ac/L2/Power': dbus.Int32(0, variant_level=1), 'Ac/L3/Power': dbus.Int32(0, variant_level=1), 'Ac/L1/Energy/Forward': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L2/Energy/Forward': dbus.Array([], signature=dbus.Signature('i'), variant_level=1), 'Ac/L3/Energy/Forward': dbus.Array([], signature=dbus.Signature('i'), variant_level=1)}

Bildschirmfoto vom 2023-01-02 23-11-17

My respect ! A very good attempt for a "first try".

Jens

**Comment by henne49** [comment]
this should be fixed now, you should see total

**Comment by stxShadow** [comment]
Yes ! Works now: 

Bildschirmfoto vom 2023-01-03 09-55-17

Only one little thing : The inverter is shown a Fronius Inverter now (right side is the tasmota inverter, left i a real Fronius):

Bildschirmfoto vom 2023-01-03 10-38-46

Any idea how to fix that ? If i use an ET112 the Fronius icon is gone.  -> but thats not a big deal

Thanks a lot ! I will do record a video on this soon :) A lot of people are interessted.

Jens

**Comment by henne49** [comment]
I checked this, I'm release 3.0 for Venus and I do not have a Fronius Logo, so maybe that is because you already have a Fronius. Is the ET112 defined as PV Inverter in DBUS?
Bildschirm­foto 2023-01-04 um 07 39 39

**Comment by henne49** [comment]
Please give me a nudge, before you create the Video, I still have to merge the changes into main, but before would like to do some testing still.

**Comment by stxShadow** [comment]
> Please give me a nudge, before you create the Video, I still have to merge the changes into main, but before would like to do some testing still.

Will do it next week i think .....

**Comment by henne49** [comment]
ok the Tasmota and Shelley as template is already in Main branch. For next I also plan a rewrite to allow for not just a summary PV inverter in Venus, but each ahoy or opendtu inverter as single instance for reporting purpose.

**Pull request merged**
